### ISSUE TITLE
Can Talk and Hear over Radio and when in the same car BUT Cant hear in person

### ISSUE THREAD

**Issue by Jimbosus** [FrazzIe/mumble-voip-fivem#57] opened 2020-09-07 17:51 UTC
We can hear and talk over the radio fine but in person we cant hear each other. When in the same vehicle it ALSO works then when we leave the vehicle it stops working again

**Comment by xxXDreddXxx** [comment] 2020-09-07 22:33
I'm having this exact issue, I switched from 1.5.2 to 1.5.3 nothing i've tried works. I'm currently using vmenu, gcphone, and trew hud though i've disabled voice on vmenu, and trew hud. It IS an esx server as well.

**Comment by anguish12** [comment] 2020-09-07 22:37
Also having the same issue, works in vehicles, not outside of them I think.

**Comment by xxXDreddXxx** [comment] 2020-09-07 23:27
This issue is now persisting into 1.5.4, I can talk to others via radio, and when we are both in the same vehicle but at no other time can I talk to other players. This is a community wide issue

**Comment by xxXDreddXxx** [comment] 2020-09-07 23:57
https://gyazo.com/898b89edfc57bf17eb78bc39071b5144

https://gyazo.com/fe76108154b7357bc2f7604f0114302b

These are two gyazo images of the only mumble script pieces appearing for me outside of it telling me chunks.

**Comment by xxXDreddXxx** [comment] 2020-09-08 00:19
https://gyazo.com/093be880a84b04e2976e4df37bc61d0d

https://gyazo.com/6541bae605f97b5edf6720a29093f0d4

https://gyazo.com/57ea37e0c07b785129922f349baed4e1

https://gyazo.com/86fa0abf9088c3c02e44c345c5d098e7

https://gyazo.com/09dd3f0c716c129438eda106c3b3db19

Its acting almost as if it cant find anyone for me to talk to.

**Comment by FrazzIe** [comment] 2020-09-08 01:53
Sending voice stuff is for specific things (radio, call, passengers) it says "Sending voice to nobody" if you are not in one of these things with another person.

The talking outside of the vehicle, call, radio etc should be handled by the chunk system, each "chunk" is a voice channel, and a player will send there voice to the chunk they are in and chunks that are nearby.

**Comment by xxXDreddXxx** [comment] 2020-09-08 01:55
Okay, but we cant talk in those chunks then?

**Comment by FrazzIe** [comment] 2020-09-08 01:56
I guess? cannot really test anything, completely in the dark with fixing these types of issues

**Comment by Jimbosus** [comment] 2020-09-08 01:57
Yeah we are running into the issue were regardless of chunk so long as wear aren't on radio or in a car we cant speak to each other
so how would we go about fixing that?

**Comment by xxXDreddXxx** [comment] 2020-09-08 01:58
Okay, thats fair. :) What would you suggest we do to troubleshoot? We have tried down grading all the way to 1.5.1, we have disabled voice in esx, vmenu, and trew hud, we are also using reignited gcphone. We cant talk in nearby chat but CAN talk when in vehicles or radio?

**Comment by FrazzIe** [comment] 2020-09-08 02:00
check if gcphone is messing with `NetworkSetVoiceChannel` or `NetworkSetTalkerProximity` or any script for that matter.
vMenu also causes conflicts with the voice menu.

**Comment by xxXDreddXxx** [comment] 2020-09-08 02:01
Gotcha, so i'll go ahead and check the gcphone. On vmenu i've disabled it but should I just rip the entire voip code out of it?

**Comment by FrazzIe** [comment] 2020-09-08 02:02
the permissions.cfg stuff should be fine, but try testing ur server with vMenu disabled to see if its the cause

**Comment by FrazzIe** [comment] 2020-09-08 02:08
also "downgrading" won't fix the issue, always be on latest release.

**Comment by xxXDreddXxx** [comment] 2020-09-08 02:09
I'll keep that in mind, thank you. I've just been tearing out my hair trying to fix this

**Comment by FrazzIe** [comment] 2020-09-08 02:10
just think how i feel seeing people having issues that i can't fix by myself, really frustrating lmao.

**Comment by xxXDreddXxx** [comment] 2020-09-08 02:27
Check it champ. Its vmenu, we had voice chat set to admin only... guess whose all having issues with it. xD

**Closed** 2020-09-12 22:39 UTC

**Comment by SpottyFilms** [comment] 2021-03-01 13:40
This is something we are still having issues with today. If we turn off vMenu it works fine though. And it only happens for one person. Very strange
